version: '3.7'

services:
  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Asia/Seoul